import type { Email, OrchestrationResult, Priority, CalendarEvent, SpamResult, SummarizerResult } from '../types/email.js';
import { summarizerAgent } from '../agents/summarizer.js';
import { replyGeneratorAgent } from '../agents/reply-generator.js';
import { spamDetectorAgent } from '../agents/spam-detector.js';
import { calendarExtractorAgent } from '../agents/calendar-extractor.js';
import { languageDetectorAgent, type LanguageResult } from '../agents/language-detector.js';

const SPAM_THRESHOLD = 0.5;

function calculatePriority(
  email: Email,
  calendarEvent: CalendarEvent | null,
  spamResult: SpamResult
): Priority {
  // High spam = low priority
  if (spamResult.isSpam) {
    return 'low';
  }
  
  // Has calendar event = high priority
  if (calendarEvent) {
    return 'high';
  }
  
  // Check subject for priority indicators
  const subject = email.subject.toLowerCase();
  const highPriorityWords = ['urgent', 'important', 'asap', 'critical', 'deadline', 'emergency'];
  const lowPriorityWords = ['fyi', 'newsletter', 'update', 'digest', 'weekly', 'monthly'];
  
  if (highPriorityWords.some(word => subject.includes(word))) {
    return 'high';
  }
  
  if (lowPriorityWords.some(word => subject.includes(word))) {
    return 'low';
  }
  
  return 'medium';
}

function buildActionsList(
  summaryResult: SummarizerResult,
  spamResult: SpamResult,
  calendarEvent: CalendarEvent | null,
  replyGenerated: boolean,
  language: LanguageResult
): string[] {
  const actions: string[] = [];
  
  actions.push(`✅ Summarized by Summarizer Agent`);
  actions.push(`🌍 Language detected: ${language.languageName} (${(language.confidence * 100).toFixed(0)}% confidence)`);
  
  if (replyGenerated) {
    if (language.language !== 'en') {
      actions.push(`✅ Reply generated by Reply Agent (in ${language.languageName})`);
    } else {
      actions.push(`✅ Reply generated by Reply Agent`);
    }
  } else if (spamResult.isSpam) {
    actions.push(`⏭️ Reply skipped (spam detected)`);
  }
  
  const spamPercent = Math.round(spamResult.score * 100);
  if (spamResult.isSpam) {
    actions.push(`🚫 Spam detected (${spamPercent}% spam probability)`);
  } else {
    actions.push(`✅ Spam check passed (${spamPercent}% spam probability)`);
  }
  
  if (calendarEvent) {
    actions.push(`✅ Calendar event extracted`);
  } else {
    actions.push(`ℹ️ No calendar event detected`);
  }
  
  return actions;
}

export async function processEmail(email: Email): Promise<OrchestrationResult> {
  const startTime = Date.now();
  
  console.log('\n🚀 Starting email orchestration...');
  console.log(`📧 From: ${email.from}`);
  console.log(`📝 Subject: ${email.subject}\n`);
  
  // Phase 1: Parallel execution of independent agents (including language detection)
  console.log('⚡ Phase 1: Running parallel agents (Summarizer, Spam Detector, Calendar Extractor, Language Detector)...');
  
  const [summaryResult, spamResult, calendarEvent, languageResult] = await Promise.all([
    summarizerAgent.run(email),
    spamDetectorAgent.run(email),
    calendarExtractorAgent.run(email),
    languageDetectorAgent.run(email),
  ]);
  
  console.log(`   ✓ Summary: ${summaryResult.summary.substring(0, 50)}...`);
  console.log(`   ✓ Spam Score: ${(spamResult.score * 100).toFixed(1)}%`);
  console.log(`   ✓ Calendar Event: ${calendarEvent ? 'Found' : 'None'}`);
  console.log(`   ✓ Language: ${languageResult.languageName} (${(languageResult.confidence * 100).toFixed(0)}%)`);
  
  // Phase 2: Conditional reply generation (with language support)
  let suggestedReply: string | null = null;
  
  if (spamResult.score < SPAM_THRESHOLD) {
    console.log(`\n💬 Phase 2: Generating smart reply in ${languageResult.languageName}...`);
    const replyResult = await replyGeneratorAgent.run(email, summaryResult, { language: languageResult });
    suggestedReply = replyResult.reply;
    console.log(`   ✓ Reply generated (${replyResult.tone} tone)`);
  } else {
    console.log('\n⏭️ Phase 2: Skipping reply generation (spam detected)');
  }
  
  // Calculate priority
  const priority = calculatePriority(email, calendarEvent, spamResult);
  
  // Build actions list
  const actionsTaken = buildActionsList(
    summaryResult,
    spamResult,
    calendarEvent,
    suggestedReply !== null,
    languageResult
  );
  
  const processingTime = Date.now() - startTime;
  console.log(`\n✨ Orchestration complete in ${processingTime}ms`);
  
  return {
    summary: summaryResult.summary,
    priority,
    suggested_reply: suggestedReply,
    spam_score: spamResult.score,
    calendar_event: calendarEvent,
    actions_taken: actionsTaken,
    processing_time_ms: processingTime,
    detected_language: {
      code: languageResult.language,
      name: languageResult.languageName,
      confidence: languageResult.confidence,
    },
  };
}

export const masterOrchestrator = {
  name: 'Email Orchestrator',
  processEmail,
};
