import type {
  Email,
  OrchestrationResult,
  Priority,
  CalendarEvent,
  SpamResult,
  SummarizerResult,
} from "../types/email.js";
import { summarizerAgent } from "../agents/summarizer.js";
import { replyGeneratorAgent } from "../agents/reply-generator.js";
import { spamDetectorAgent } from "../agents/spam-detector.js";
import { calendarExtractorAgent } from "../agents/calendar-extractor.js";

const SPAM_THRESHOLD = 0.5;

function calculatePriority(
  email: Email,
  calendarEvent: CalendarEvent | null,
  spamResult: SpamResult
): Priority {
  // High spam = low priority
  if (spamResult.isSpam) {
    return "low";
  }

  // Has calendar event = high priority
  if (calendarEvent) {
    return "high";
  }

  // Check subject for priority indicators
  const subject = email.subject.toLowerCase();
  const highPriorityWords = [
    "urgent",
    "important",
    "asap",
    "critical",
    "deadline",
    "emergency",
  ];
  const lowPriorityWords = [
    "fyi",
    "newsletter",
    "update",
    "digest",
    "weekly",
    "monthly",
  ];

  if (highPriorityWords.some((word) => subject.includes(word))) {
    return "high";
  }

  if (lowPriorityWords.some((word) => subject.includes(word))) {
    return "low";
  }

  return "medium";
}

function buildActionsList(
  summaryResult: SummarizerResult,
  spamResult: SpamResult,
  calendarEvent: CalendarEvent | null,
  replyGenerated: boolean
): string[] {
  const language = {
    language: summaryResult.language || "en",
  };
  const displayName = new Intl.DisplayNames(["en"], { type: "language" }).of(
    language.language
  );
  const actions: string[] = [];

  actions.push(
    `✅ Summarized by Summarizer Agent (Length: ${summaryResult.summary.length} chars)`
  );
  actions.push(`🌍 Language detected: ${displayName} (${language.language})`);

  if (replyGenerated) {
    if (language.language !== "en") {
      actions.push(`✅ Reply generated by Reply Agent (in ${displayName})`);
    } else {
      actions.push(`✅ Reply generated by Reply Agent`);
    }
  } else if (spamResult.isSpam) {
    actions.push(`⏭️ Reply skipped (spam detected)`);
  }

  const spamPercent = Math.round(spamResult.score * 100);
  if (spamResult.isSpam) {
    actions.push(`🚫 Spam detected (${spamPercent}% spam probability)`);
  } else {
    actions.push(`✅ Spam check passed (${spamPercent}% spam probability)`);
  }

  if (calendarEvent) {
    actions.push(`✅ Calendar event extracted`);
  } else {
    actions.push(`ℹ️ No calendar event detected`);
  }

  return actions;
}

export async function processEmail(email: Email): Promise<OrchestrationResult> {
  const startTime = Date.now();

  console.log("\n🚀 Starting email orchestration...");
  console.log(`📧 From: ${email.from}`);
  console.log(`📝 Subject: ${email.subject}\n`);

  // Phase 1: Fast Spam Check
  console.log("⚡ Phase 1: Running fast spam check...");
  const spamResult = await spamDetectorAgent.run(email);
  console.log(`   ✓ Spam Score: ${(spamResult.score * 100).toFixed(1)}%`);

  // Phase 2: Parallel execution of heavy agents
  console.log(
    "⚡ Phase 2: Running parallel agents (Summarizer, Calendar Extractor, Reply Generator)..."
  );

  const tasks: Promise<any>[] = [
    summarizerAgent.run(email),
    calendarExtractorAgent.run(email),
  ];

  // Only run reply generation if not spam
  let replyPromise: Promise<any> | null = null;
  if (spamResult.score < SPAM_THRESHOLD) {
    console.log(
      `   Detailed classification passed, triggering reply generation...`
    );
    replyPromise = replyGeneratorAgent.run(email, null); // No summary needed now
    tasks.push(replyPromise);
  } else {
    console.log("   🚫 High spam score detected, skipping reply generation");
  }

  const results = await Promise.all(tasks);
  const summaryResult: SummarizerResult = results[0];
  const calendarEvent: CalendarEvent | null = results[1];
  let replyResult: any = null;

  if (replyPromise) {
    replyResult = results[2];
  }

  const languageResult = {
    language: summaryResult.language || "en",
  };
  const displayName = new Intl.DisplayNames(["en"], { type: "language" }).of(
    languageResult.language
  );

  console.log(`   ✓ Summary: ${summaryResult.summary.substring(0, 50)}...`);
  console.log(`   ✓ Calendar Event: ${calendarEvent ? "Found" : "None"}`);
  console.log(`   ✓ Language: ${displayName} (${languageResult.language})`);

  let suggestedReply: string | null = null;
  if (replyResult) {
    suggestedReply = replyResult.reply;
    console.log(`   ✓ Reply generated (${replyResult.tone} tone)`);
  } else if (spamResult.score >= SPAM_THRESHOLD) {
    console.log("\n⏭️ Reply skipped (spam detected)");
  }

  // Calculate priority
  const priority = calculatePriority(email, calendarEvent, spamResult);

  // Build actions list
  const actionsTaken = buildActionsList(
    summaryResult,
    spamResult,
    calendarEvent,
    suggestedReply !== null
  );

  const processingTime = Date.now() - startTime;
  console.log(`\n✨ Orchestration complete in ${processingTime}ms`);

  return {
    summary: summaryResult.summary,
    priority,
    suggested_reply: suggestedReply,
    spam_score: spamResult.score,
    calendar_event: calendarEvent,
    actions_taken: actionsTaken,
    processing_time_ms: processingTime,
    detected_language: {
      language: languageResult.language,
    },
  };
}

export const masterOrchestrator = {
  name: "Email Orchestrator",
  processEmail,
};
